spring.application.name=demo
server.port=8081

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always

mybatis.configuration.map-underscore-to-camel-case=true

chat.server.enabled=true
chat.server.port=8080
chat.server.path=/ws/chat

app.cors.allowed-origins=http://localhost:5173,https://liaoke.org

springdoc.swagger-ui.path=/swagger-ui.html
